{{ if .Values.usePersistentVolumes }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Namespace }}-datastore-db
spec:
  storageClassName: {{ .Values.storageClassName }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.dataStoreDbPersistentDiskSizeGB }}G
{{ end }}
