{{ if not .Values.privateRegistryEnable }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.imagePullSecret | default "container-registry" }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.dockerconfigjson }}
{{ end }}
