{{ if not .Values.solrDisabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: solr
spec:
  replicas: 1
  revisionHistoryLimit: 2
  strategy:
    type: Recreate
  selector:
    matchLabels: {app: solr}
  template:
    metadata:
      labels:
        app: solr
    spec:
      initContainers:
      - name: permissions
        image: alpine
        command:
        - sh
        - "-c"
        {{ if .Values.centralizedInfraOnly }}
        - |
          mkdir -p /opt/solr/server/solr &&\
          chown -R 8984:8984 /opt/solr &&\
          ls -lah /opt/solr
        {{ else }}
        - |
          mkdir -p /opt/solr/server/solr/ckan/data
          chown -R 8983:8983 /opt/solr/server/solr/ckan/data &&\
          ls -lah /opt/solr/server/solr/ckan/data
        {{ end }}
        securityContext:
          runAsUser: 0
        volumeMounts:
        - name: ckan-data
          mountPath: /opt/solr/server/solr
          subPath: solr-ckan-data
      containers:
      - image: {{ if .Values.centralizedInfraOnly }}{{ .Values.solrcloudImage | quote }}{{ else }}{{ .Values.solrImage | quote }}{{ end }}
        name: solr
        {{ if .Values.centralizedInfraOnly }}
        args: [solr, start, -c, -f]
        {{ end }}
        ports:
        - containerPort: 8983
        {{ if .Values.solrResources }}
        resources: {{ .Values.solrResources }}
        {{ end }}
        volumeMounts:
        - name: ckan-data
          mountPath: /opt/solr/server/solr
          subPath: solr-ckan-data
      volumes:
      - name: ckan-data
      {{ if .Values.usePersistentVolumes }}
        persistentVolumeClaim:
          claimName: {{ .Release.Namespace }}-solr
      {{ else }}
        hostPath:
          path: /var/ckan-cloud-{{ .Release.Namespace }}
          type: DirectoryOrCreate
      {{ end }}
{{ end }}
